baseURL = 'https://m319.frickelbude.ch'
languageCode = 'de-ch'
title = 'Modul 319: Applikationen entwerfen und implementieren'

[module]
[[module.imports]]
path = 'github.com/McShelby/hugo-theme-relearn'
