baseURL = 'https://m319.frickelbude.ch'
languageCode = 'de-ch'
title = 'Modul 319: Applikationen entwerfen und implementieren'

[minify]
minifyOutput = true

[params]
disableInlineCopyToClipBoard = true
math.disabled = false
openapi = false
showVisitedLinks = true
themeVariant = 'red'
hideAuthorDate = true

[params.author]
name = 'Patrick Bucher, BBZW Sursee'

[module]
[[module.imports]]
path = 'github.com/McShelby/hugo-theme-relearn'
